text("3 cups all-purpose flour")
text("3 cups granulated sugar")
text("1/2 cup cornstarch")
text("1/2 cup unsweetened cocoa powder")
text("1 tablespoon baking soda")
text("1½ teaspoons baking powder")
text("1½ teaspoons salt")
text("4 large eggs")
text("1½ cups buttermilk")
text("1¼ cups warm water")
text("1/2 cup vegetable oil")
text("1 teaspoon vanilla extract")
text("1 teaspoon distilled white vinegar")
text("2 tablespoons red food coloring")
